module.exports = ["First I went left, he did too. Then I went right, and he did too. Then I went left again, and he went to buy a hot dog.",
    "It’s Zlatan-style.",
    "Well... I don’t know…you’ll have to ask your wife about that",
    "Absolutely not. I have ordered a plane. It is much faster.",
    "What Carew does with a football, I can do with an orange.",
    "Arsene Wenger asked me to have a trial with Arsenal when I was 17. I turned it down. Zlatan doesn’t do auditions.",
    "Come over to my house with your sister, baby, and I’ll show you who’s gay!",
    "Nothing, she already has Zlatan.",
    "One thing is for sure, a World Cup without me is nothing to watch so it is not worthwhile to wait for the World Cup.",
    "An injured Zlatan is a pretty serious thing for any team.",
    "I haven't met her yet. But when I do, I'll date her.",
    "We are looking for an apartment [in Paris]. If we don't find anything, then I'll probably just buy the hotel.",
    "According to my calculations it is possible to lose nine points in only three games.",
    "Zlatan Jr.",
    "You could have punched me in the face, I wouldn’t have noticed",
    "I don’t do that stuff. For me it is romance and love…right?",
    "I’m like Muhammed Ali. When he said he would knock someone out in the fourth round, he did it.",
    "It was the fault of David Trezeguet, who made me do one drink of vodka after another. I slept in the bathtub. Now I hold my vodka much better.",
    "I can play in the 11 positions because a good player can play anywhere on the pitch.",
    "I felt like crap when I was sitting in the locker room with Guardiola staring at me like I was an annoying distraction, an outsider. It was nuts. He was a wall, a stone wall. I didn’t get any sign of life from him and I was wishing myself away every moment with the team.",
    "Then Guardiola started his philosopher thing. I was barely listening. Why would I? It was advanced bullshit about blood, sweat and tears, that kind of stuff.",
    "Guardiola was staring at me and I lost it. I thought 'there is my enemy, scratching his bald head!'. I yelled to him: 'You have no balls!' and probably worse things than that.",
    "When you buy me, you are buying a Ferrari. If you drive a Ferrari you put premium fuel in the tank, you drive onto the motorway and you floor the accelerator. Guardiola filled up with diesel and went for a spin in the countryside. If that’s what he wanted, he should have bought himself a Fiat from the start.",
    "Mourinho is Guardiola’s opposite. If Mourinho brightens up the room, Guardiola pulls down the curtains and I guessed that Guardiola now tried to measure himself with him.",
    "An injured Zlatan is a pretty serious thing for any team.",
    "At Barca, players were banned from driving their sports cars to training. I thought this was ridiculous – it was no one’s business what car I drive – so in April, before a match with Almeria, I drove my Ferrari Enzo to work. It caused a scene.",
    "I like fireworks too, but I set them off in gardens or kebab stands. I never set fire to my own house.",
    "You bought a Ferrari but you drive it like a Fiat",
    "Jose Mourinho is a big star... he's cool. The first time he met (my wife) he whispered to her: 'Helena you have only one mission. Feed Zlatan, let him sleep, keep him happy' The guy says what he wants. I like him.",
    "He formed an attachment to me even before we met. He would become a guy I was basically willing to die for.",
    "I don't give a shit who wins, I'm going on holiday.",
    "Only God knows... You’re talking to him now.",
    "I can't help but laugh at how perfect I am.",
    "One time I got dressed in all black, Rambo-style, and took a massive pair of bolt-cutters and nicked a military bike.",
    "I've never heard this question before, I think it's only you who doesn't understand.",
    "Whenever life’s at a standstill I need some action. I always drive like a maniac. I’ve done 325 kilometres an hour in my Porsche Turbo and left the cops eating my dust.",
    "I didn’t injure you on purpose, and you know that. If you accuse me again I’ll break both your legs, and that time it will be on purpose.",
    "If he did join he would have to get used to the fact that Zlatan scores even better goals than him."
];
